### PR TITLE
chore(deps): bump @actions dependencies

### PR DESCRIPTION
**Pull request by tbouffard**
### Description

Bump @actions/core from 1.6.0 to 1.10.0
Bump @actions/github from 5.0.0 to 5.1.1

The new `@actions/core` version avoids to log warnings about "the set-output command is deprecated". See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

### Testing

Dependabot cannot correctly bump `@actions` dependencies as it doesn't rebuild the JS code actually used at runtime by the action. So this Pull Request supersedes  #218

### CODE REVIEW

**Comment by tbouffard** [comment]
Hi @jef 
did you have time to have a look at this PR?
It is quite old and newer versions of the dependencies are available. I can update the PR if needed.
Thanks

**Review by jef — DISMISSED** [review]

**Comment by jef** [comment]
> Hi @jef 
> 
> did you have time to have a look at this PR?
> 
> It is quite old and newer versions of the dependencies are available. I can update the PR if needed.
> 
> Thanks

Hey! Sorry for getting back late @tbouffard, actually just seeing this now. I'm going to run the workflows when I get on the computer tomorrow.

Feel free to update or I can merge as-is. Thanks for doing this!

**Comment by tbouffard** [comment]
OK, thanks for the feedback. I am going to update the dependencies to the latest versions.

**Comment by tbouffard** [comment]
Hi @jef I have been able to update a dependency but @actions/github cannot be bumped to v6 for now.
The ncc command failed:
```
ncc: Version 0.33.3
ncc: Compiling file index.js into CJS
Error: Module parse failed: Unexpected token (42:9)
File was processed with these loaders:
 * ./node_modules/@vercel/ncc/dist/ncc/loaders/empty-loader.js
 * ./node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js
 * ./node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js
You may need an additional loader to handle the result of these loaders.
| var userAgentTrail = `octokit-core.js/${VERSION} ${(0, import_universal_user_agent.getUserAgent)()}`;
| var Octokit = class {
>   static {
|     this.VERSION = VERSION;
|   }
```

I can provide another PR that will build the action with Node 20, bump dev dependencies and @actions/github. 
It could also update the `action.yml `file to declare that the action must run with Node 20. It currently declares Node 16 https://github.blog/changelog/2024-09-25-end-of-life-for-actions-node16/
Tell me if you are interesting in such a PR.

**Comment by jef** [comment]
Hey @tbouffard, that's okay, let's start with this for now and I can update this action. I'll want to do some updating with Volta and on some other repos. Thanks for this awesome help! :)

**Pull request merged**
